import { ReactAriaRouterProvider } from "@/shared/ui/react_aria/react_aria_router_provider";
import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          "bg-gradient-to-br from-indigo-50 via-white to-violet-50 min-h-[100dvh]"
        }
      >
        <ReactAriaRouterProvider>
          <nav className="border-b border-b-gray-400 p-2">
            <Link href="/">Home</Link>
            <Link href="/ui/headless">UI-Headless</Link>
          </nav>
          {children}
        </ReactAriaRouterProvider>
      </body>
    </html>
  );
}
